version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    environment:
      - DB_TYPE=mysql
      - DB_MYSQLDB_DATABASE=scooller_n8n
      - DB_MYSQLDB_USER=scooller_n8nuser
      - DB_MYSQLDB_PASSWORD=(gZBAK?{y_0b
      - DB_MYSQLDB_HOST=mysql
      - DB_MYSQLDB_PORT=3306
      - N8N_HOST=scooller.it.eu.org
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=rxwWte4ALzRE/jmhUO2+4uN+0EY6BTunv7bhYxo4/C4=
      - N8N_LOG_LEVEL=info
      - N8N_ENCRYPTION_KEY=pon_aqui_una_clave_larga_y_unica
      - N8N_WEBHOOK_URL=http://scooller.it.eu.org/webhook
      - N8N_TIMEZONE=UTC
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: n8n_mysql
    environment:
      - MYSQL_DATABASE=scooller_n8n
      - MYSQL_USER=scooller_n8nuser
      - MYSQL_PASSWORD=(gZBAK?{y_0b
      - MYSQL_ROOT_PASSWORD=root_password_seguro
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  n8n_data:
  mysql_data: